s = 'CCGCTATTTTGTGTCGGGCGCTTACTTTAGGCTTGTGAAAGCTGTGCTAGTAAACCTCGCGTAGAAGGCTAGGTAATCCACATGTTGCCTATGTGATTTGACGCACCTAGTCCAGATTACATAAGCGTTCAAGACTTAGTACACCCACCAACCGTTCCTTCCAATACCGTACCCCTGGCTGGTTGATTACGTTCCTTAGAGCTAGTCTTTACCTGAACCCGAGAAAATGGGATGTACGGGCATTTAAAAGCGAATTAGTTCGGGCGAGGCGGCTCAGGGATCTGTACCTTGAGCTAGTACGGCACGGTTCCGTTACGGTATGAGATCAAATTAATTGCAAAGTTCCTCCACCAGGATACTACCTACGGGTTGGAAAGGGTTGAGAGTCCCCCTACCCCATTGTACATTCAGGGGGCGTCATTGTATCCCGTAATCGGAAGAACCCGCCTGGCGCCAAGTAGTGAGTGCACAACCGTGGGCCCGATGAGATGCCAACATACGCACCGCCTAGTGCTGTTGGGCTGGAGGTTGCGTCATTATGTAGCTCCAACGCTCGGTCGCCCTTACATGAGTTTTGGAGGTTAGAAGGGCTCCGGAGATGAGACACTAAATGTGTTTGCGCCGCGGTTATTGCAGTGTCCATGCCCTCACTAGACTACTTGATCGTGTTAACCGAAACTGCACTGCAACACCCTTTTCAGGTCTGGTCCATTCTTCCGTGGTGTTTGGTGGATGGACACACAGGGTCGCTTTTGTGGTAGTTGTTACCGCGATCCTATACATTGATGTTTACCCTACATGTAGGGGCGCGGACCCAGTAGGGTCCGATAGAAATTATGATAGCTCTTTGATATCAGACGGCCTGAAGGTCGATACAGCGCGGGCCCCTAGACACCACCGCTTCCTCTCCTGGTGGCGGGTTCCCAAGGAGAGTGCGTTCTTACTTTCTAAGGG'
A = 0
C = 0
G = 0
T = 0
for letter in s:
    if letter == 'A':
        A = A + 1;
    if letter == 'C':
        C = C + 1;
    if letter == 'G':
        G = G + 1;
    if letter == 'T':
        T = T + 1;
   
        
print A
print C
print G
print T
